// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  editoras: Editora[] = [];
  livros: Livro[] = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then(livros => {
      this.livros = livros;
    });
  }

  excluir = (codigoLivro: string) => {
    this.servLivros.excluir(codigoLivro).then(() => {
      this.servLivros.obterLivros().then(livros => {
        this.livros = livros;
      });
    });
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora) ?? '';
  }
}

<main class="container">
    <h2>Lista de Livros</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Título</th>
          <th scope="col">Resumo</th>
          <th scope="col">Autores</th>
          <th scope="col">Editora</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.titulo }}</td>
          <td>{{ livro.resumo }}</td>
          <td>
            <ul class="list-unstyled">
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
        </tr>
      </tbody>
    </table>
  </main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import { ControleLivros } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

function LinhaLivro({ livro, excluir }) {
    const nomeEditora = ControleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr>
            <td>
                <button onClick={() => excluir(livro.codigo)}>Excluir</button>
            </td>
            <td>{livro.codigo}</td>
            <td>{nomeEditora}</td>
            <td>{livro.titulo}</td>
            <td>{livro.resumo}</td>
            <td>
                <ul>
                    {livro.autores.map((autor, index) => (
                        <li key={index}>{autor}</li>
                    ))}
                </ul>
            </td>
        </tr>
    );
}

export default function LivroLista() {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        if (!carregado) {
            ControleLivros.obterLivros()
                .then(livrosObtidos => {
                    setLivros(livrosObtidos);
                    setCarregado(true);
                })
                .catch(error => {
                    console.error('Erro ao obter livros:', error);
                });
        }
    }, [carregado]);

    const excluir = (codigoLivro) => {
        ControleLivros.excluir(codigoLivro)
            .then(success => {
                if (success) {
                    setCarregado(false);
                } else {
                    console.error('Erro ao excluir livro: Ocorreu um erro ao excluir o livro');
                }
            })
            .catch(error => {
                console.error('Erro ao excluir livro:', error);
            });
    };
    
    return (
        <main>
            <h1>Lista de Livros</h1>
            <table>
                <thead>
                    <tr>
                        <th>Ações</th>
                        <th>Código</th>
                        <th>Editora</th>
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro) => (
                        <LinhaLivro key={livro.codigo} livro={livro} excluir={excluir} />
                    ))}
                </tbody>
            </table>
        </main>
    );
}
